### ISSUE TITLE
Updates for kOS v1.0.1

### ISSUE THREAD

**Issue by ElWanderer** [ElWanderer/kOS_scripts#65]
(ticked items have been implemented/closed but not tested):
- [x] remove WAITs following staging (if any exist) now that happens automatically
- [x] try out the new warp behaviours e.g. being able to kill warp by a command `KUNIVERSE:TIMEWARP:CANCELWARP()`
- [x] the improved time handling may mean our MET formatting can be simplified
- [x] consider user input (into the terminal) instead of "hard-coding" parameters - now under issue #78
- [x] there is now a `CHUTESSAFE` pseudo action group for deploying only those parachutes that can be safely deployed. Could replace the parachute checking with `IF NOT CHUTESSAFE { CHUTESSAFE ON. }` - now under issue #79 
- [x] similarly, it looks like we can now refer to landing legs via the `LEGS` action group instead of using `GEAR`. - now under issue #79

**Comment by ElWanderer** [comment]
Added issue #78 for user input. Considering that a major change to my scripts, so out of scope for now.
